export const USER_ADD_REQUEST = 'USER_ADD_REQUEST';
export const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';

export const USER_EDIT = 'USER_EDIT';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';

export const INIT_USER_LIST_REQUEST = 'INIT_USER_LIST_REQUEST';
export const INIT_USER_LIST_SUCCESS = 'INIT_USER_LIST_SUCCESS';

// export const RECEIVE_USER = 'RECEIVE_USER';
// export const REQUEST_USER = 'REQUEST_USER';
//
// export const USER_REQUEST = 'USER_REQUEST'
// export const USER_SUCCESS = 'USER_SUCCESS'
// export const USER_FAILURE = 'USER_FAILURE'

